### ISSUE TITLE
[Impovments] Mod Builder, and mod Dev

### ISSUE THREAD

**Issue by KnatteAnka** [mechanistry/timberborn-modding#1]
# Editor
## Stage location for Assetbundle
Compared to Thunderkit that has the completed files in the project folder structure it resulted in longer build times because my doc was on a mechanical disk instead of a raided ssd as the project is on.

### Suggestion:
i see some options:
* maybe have a Staging folder where the mod is placed before moved to mods folder
* Still staging folder but add Commandline to change mods location so it can launch with commandline to the staging folder to separate WIP mod folder and Stable play mods folder.

## Checkbox confirm remove of files in mod dir
if the check box is pressed it skips the build anyway popup and builds straight away

## Checkbox to Launch game when built
when its built it should be able to launch the game ether by selecting game exe or by steam command (default? if empty?)

## Autolaunch Specific save
Add a select box to select Settlement and Save to load when built.

## Export DLL

~~When using export DLL from this dep its not 100% correct when ripped game assets to see how existing buildings work
Components gets different guid compared to when Thunderkit exports dll:s~~

Hmm more Debugging is needed

---
# Ingame:

## Mod list ingame
This should only show when the modlist is changed compared to last run

## Mod logging
Mod version should be logged so its possible to see from log if a mod is to low version/not newest

**Comment by KnatteAnka** [comment]
~~After some more investigation its noted that the approach of generating GUID for DLL:s is not the same as Assetripper and Thunderkit this does so Existing mods cant be converted easy and that asset ripped files cant be viewed without TK~~

~~Twiners approwal to use TK code as reference for GUID creation
https://discord.com/channels/558398674389172225/888491376143134760/1256285576106217543~~

~~Start of discussion:
https://discord.com/channels/558398674389172225/888491376143134760/1256283173139251293~~

Done:

**Comment by KnatteAnka** [comment]
~~BlockobjectEditorplugin should be included in this mod pack in the compiled Dll:s
File:
https://discord.com/channels/558398674389172225/888491376143134760/1256332258105753611~~

Done.

**Comment by KnatteAnka** [comment]
eMka needed Timberborn.BlockSystem.dll.meta to fix DLL import
including a Thunderkit version (added.json to allow upload)

[Timberborn.BlockSystem.dll.meta.json](https://github.com/user-attachments/files/16036294/Timberborn.BlockSystem.dll.meta.json)

**Comment by mwierzchos** [comment]
We aren't planning to add staging build directory for now. Same for changes in initial mod manager, we need more feedback from the players.
The rest is done.
