### ISSUE TITLE
[Bug] Workshop_data replaced at modbuild

### ISSUE THREAD

**Issue by KnatteAnka** [mechanistry/timberborn-modding#3]
## Description
When a mod is built it removes everything including Workshop_data.json

## Result:
Updated settings and config is lost that mod was uploaded.

## Example Solution:
When a mod is built before the mod folder is cleared it should check and import existing Workshop_data.json to Project Data folder.
This way any config and settings is retained automagical.

**Comment by mwierzchos** [comment]
Fixed alognside #1 changes
